$(document).ready(function(){
	$("#nav1").mouseenter(function(){
		$("#arrow1").css("visibility","visible");
	});
	$("#nav1").mouseleave(function(){
		$("#arrow1").css("visibility","hidden");
	});
	$("#nav2").mouseenter(function(){
		$("#arrow2").css("visibility","visible");
	});
	$("#nav2").mouseleave(function(){
		$("#arrow2").css("visibility","hidden");
	});
	$("#nav3").mouseenter(function(){
		$("#arrow3").css("visibility","visible");
	});
	$("#nav3").mouseleave(function(){
		$("#arrow3").css("visibility","hidden");
	});
	$("#nav4").mouseenter(function(){
		$("#arrow4").css("visibility","visible");
	});
	$("#nav4").mouseleave(function(){
		$("#arrow4").css("visibility","hidden");
	});
});